### PR TITLE
AcmInlineStatusGroup component + add unknown status to AcmInlineStatus

### PR DESCRIPTION
**Pull request by showeimer**
Screen Shot 2021-02-03 at 6 09 27 PM

### CODE REVIEW

**Comment by showeimer** [comment]
@jamestalton any idea what this new check is for `dco — Commits in PR missing Signed-off-by` ?

**Review by jamestalton — APPROVED** [review]
lgtm

**Review by richiepiya — APPROVED** [review]
I spoke to Jacki a few months ago and she asked me to make the status order: `success, in_progress, warning, error` for app-ui. Has this order been changed? Aside from that, it looks good!

Screen Shot 2021-02-04 at 10 04 27 AM

**Comment by showeimer** [comment]
@richiepiya she gave me a few options about the order, I wasn't sure either.  But I am good with that order, I'll throw the Unknown at the end

**Review by KevinFCormier — APPROVED** [review]
Looks great! The only thing I found myself wondering is whether it would make sense to have a minimum width that covers the single-digit case. When the count is 1, the pill looks a little squished.

**Pull request merged**
