### PR TITLE
make AutoRefreshSelect customizable

### PR DESCRIPTION
**Pull request by RobDolares**
Related issue: https://github.com/open-cluster-management/backlog/issues/10776

Allows for user to customize their initial refresh time interval, all interval values, as well as cookie for local storage.

### CODE REVIEW

**Review by showeimer — COMMENTED** [review]
@willkutler @KevinFCormier Cluster UI doesn't use the AutoRefreshSelect component; could you both review these changes to see if it works for your teams?

**Comment by KevinFCormier** [comment]
I wasn't able to participate in the discussion about this, so I'm not sure if it matches what was decided. @birsanv and @chenz4027 can you review please?

Is the plan that we will use `initRefreshTime` and `refreshIntervalCookie` so that app lifecycle has an independent saved refresh setting from any other part of the UI?

**Review by birsanv — APPROVED** [review]
lgtm

**Review by chenz4027 — APPROVED** [review]
Thanks for the change. LGTM!

**Pull request merged**
