### PR TITLE
Add new launch options for Visual Web Terminal

### PR DESCRIPTION
**Pull request by mark-nc**
Changes for https://github.com/open-cluster-management/backlog/issues/13568

### CODE REVIEW

**Comment by mark-nc** [comment]
From local run of Demo storybook

Left nav now will launch VWT in a new browser tab

image

Header icon added for Visual Web Terminal dropdown

image

And the dropdown open

image

**Review by jlpadilla — DISMISSED** [review]
/lgtm
/hold

I see a few errors from the tests, but the tests passed, please double check before merging.  https://travis-ci.com/github/open-cluster-management/ui-components/builds/230901059#L886

**Review by KevinFCormier — APPROVED** [review]
Great! Thanks, Mark.

**Comment by mark-nc** [comment]
@jlpadilla just for documentation....the errors in the test run were there even before my PR, but as you said, the tests all passed.

**Pull request merged**
